NovelT/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name ="home"
urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('register/',views.register_user,name='register'),
    path('profile/',views.user_profile, name = 'profile'),
    path('detail/<int:id>', views.book_detail, name='book-detail'),
    path('edit-profile', views.edit_profile, name = 'edit-profile'),
    path('afterRegister/',views.afterRegister,name='afterRegister'),

]

 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinLengthValidator
# Create your models here.

class Profile(models.Model):

    # for testing purpose i have set blank = True

    user        =   models.OneToOneField(User, on_delete = models.CASCADE, null = True)
    age         =   models.IntegerField(blank = True, null = True)
    location    =   models.CharField(max_length = 50, blank = True)
    occupation  =   models.CharField(max_length = 50, blank = True)
    bio         =   models.TextField(blank = True)
    profile_pic =   models.ImageField(default = 'default/default.jpg', upload_to="profile_pic", null = True, blank = True)
    pref_genere  =   models.CharField(max_length = 100, blank = True)

    def __str__(self):
        return str(self.user)

@receiver(post_save, sender = User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)
        print("Profile created!")

# post_save.connect(create_profile, sender = User)


@receiver(post_save, sender = User)
def update_profile(sender, instance, created, **kwargs):

    if created == False:
        instance.profile.save()
        print("Profile updated")

# post_save.connect(update_profile, sender = User)



class Book(models.Model):

    user        = models.ManyToManyField(User, blank = True)
    title       = models.CharField(max_length = 100, null = True)
    author      = models.CharField(max_length = 100, null = True)
    author_bio  = models.TextField(null = True,blank = True)
    isbn        = models.CharField(max_length = 10, validators = [MinLengthValidator(10)], null =True)
    book_image  = models.ImageField(upload_to = 'book_covers/', default = 'default.jpg')
    genere      = models.TextField(null = True, blank = True)
    synopsis    = models.TextField(null = True, blank = True)

    def __str__(self):
        return self.title




class Status(models.Model):
    class Meta:
            unique_together = ('user', 'books',)

    CHOICES = (('1', 'Intrested'),
                ('2', 'Read'),
                 ('3', 'Reading'),)


    # user        = models.OneToOneField(User, on_delete = models.CASCADE, null = True)
    # books       = models.OneToOneField(Book,  on_delete = models.CASCADE, null = True)
    # user        = models.ManyToManyField(User)
    # books       = models.ManyToManyField(Book)
    user                = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    books               = models.ForeignKey(Book,  on_delete = models.CASCADE, null = True)
    status_of_book      = models.CharField(choices = CHOICES,max_length=1)

    def __str__(self):
        return str(self.books)

class Ratings(models.Model):

    class Meta:
        unique_together = ('user', 'book')

    user        = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    book        = models.ForeignKey(Book, on_delete = models.CASCADE, null = True)
    rating      = models.CharField(max_length=1, null = True)

    def __str__(self):
        return (f"{self.user} | {self.book} | {self.rating} ")


class PredictedBooks(models.Model):
    user            = models.ForeignKey(User, on_delete = models.CASCADE, null = True, unique = True)
    prediction      = models.TextField(null=True)
    
    def __str__(self):
        return str(self.user)

home/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput, TextInput
from .models import Profile

class CreateUserForm(UserCreationForm):
    class Meta:

        model = User


        fields = [
                    'username',
                    'email',
                    'password1',
                    'password2',
        ]

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),

        }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile

        fields = [
                    'age',
                    'location',
                    'occupation',
                    'bio',
                    'profile_pic',
        ]



class UserUpdateForm(forms.ModelForm):


    class Meta:
        model = User

        fields = [
                    'username',
                    'email',
                    'first_name',
                    'last_name',
        ]

        help_texts = {
            'username': None,
        }

home/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm,UserUpdateForm, UserProfileForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Profile, Book, Status, Ratings, PredictedBooks
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import IntegrityError
# Create your views here.

@login_required(login_url = 'home:login')
def home(request):
    try:
    
        user_intrested_books = get_intrested_books(request)
        all_books = get_all_books(request)
        reading_books = get_reading_books(request)

        if request.method == 'POST':
            test = request.POST['test']
            print(test)
            print(test)

        page = request.GET.get('page', 1)
        paginator = Paginator(all_books, 4)
        paginator_two = Paginator(user_intrested_books, 4)
        paginator_three = Paginator(reading_books, 4)
        
        try:
            all_books = paginator.page(page)
            user_intrested_books = paginator_two.page(page)
            reading_books = paginator_three.page(page)

        except PageNotAnInteger:
            all_books = paginator.page(1)
            user_intrested_books = paginator_two.page(page)
            reading_books = paginator_three.page(page)

        except EmptyPage:
            all_books = paginator.page(paginator.num_pages)


    except:
        redirect('home:home')

    context = {
        'user_intrested_books': user_intrested_books,
        'all_books': all_books,
        'reading_books': reading_books,
        
        
    }
    return render(request, 'home/home.html', context)
	

def login_user(request):
    user = request.user

    if user.is_authenticated:
        logout_user(request)
    else:
        if request.method == 'POST':
           username = request.POST.get('username')
           password = request.POST.get('password')
           user = authenticate(username = username, password = password)

           if user is not None:
            login(request, user)
            return redirect('home:home')
           else:
            messages.info(request, 'Usernmae OR Password is wrong.')

    context = {
    }
    
    return render(request, 'home/login.html', context)

@login_required(login_url = 'home:login')
def logout_user(request):
    logout(request)
    return redirect('home:login')

def register_user(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user  = form.cleaned_data.get('username')
            password  = form.cleaned_data.get('password1')
            # messages.success(request, 'Account is Created for' + user )
            # return redirect('home:login')
            user = authenticate(username = user, password = password)
            if user is not None:
                login(request, user)
                return redirect('home:afterRegister')
    else:
        form = CreateUserForm()


    context = {
        'form' : form,
    }

    return render(request,'home/register.html',context)

@login_required(login_url = 'home:login')
def afterRegister(request):

    if request.method == 'POST':
        pref_gen = request.POST.get('test')
        print(pref_gen)
        print(type(pref_gen))
        profile = Profile.objects.get(user = request.user)
        profile.pref_genere = pref_gen
        profile.save() 
        return redirect('home:edit-profile')

    return render(request,'home/afterRegister.html')

def user_profile(request):

    user_intrested_books = get_intrested_books(request)
    all_books = get_all_books(request)
    reading_books = get_reading_books(request)

    page = request.GET.get('page', 1)
    paginator = Paginator(all_books, 4)
    paginator_two = Paginator(user_intrested_books, 4)
    paginator_three = Paginator(reading_books, 4)
    

    pref_gen = Profile.objects.get(user = request.user);  #TO DISPLAY GENERS THAT USER LIKE
    if pref_gen.pref_genere:
        pref_gen_list = pref_gen.pref_genere;
        pref_gen_list = pref_gen_list.split(',')
        pref_gen_list = [gen.capitalize() for gen in pref_gen_list]
    else:
        pref_gen_list = ""

    try:
        all_books = paginator.page(page)
        user_intrested_books = paginator_two.page(page)
        reading_books = paginator_three.page(page)

    except PageNotAnInteger:
        all_books = paginator.page(1)
        user_intrested_books = paginator_two.page(page)
        reading_books = paginator_three.page(page)

    except EmptyPage:
        all_books = paginator.page(paginator.num_pages)

    
    context = {
        'user_intrested_books': user_intrested_books,
        'all_books': all_books,
        'reading_books': reading_books,
        'pref_gen_list': pref_gen_list,
    }
        
   
    return render(request, 'home/profile.html', context)

def edit_profile(request):
    if request.method == 'POST':
        user_form       = UserUpdateForm(data =request.POST or None, instance = request.user)
        profile_form    = UserProfileForm(request.POST, request.FILES, instance = request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,f"your account is updated")
            return redirect('home:profile')
    else:
        user_form       = UserUpdateForm(instance = request.user)
        profile_form    = UserProfileForm(instance = request.user.profile)
        redirect('home:home')
        
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'home/edit-profile.html', context)


def book_detail(request, id):
    try:

        book = Book.objects.get( id = id)

        book_status = request.POST.get('read_btn')

        print(book_status)

        if book_status is not None:
            Status.objects.create(user = request.user, books = book, status_of_book = book_status)
    except:
        redirect('home:home')
        
    context = {
        'book': book,
    }

    return render(request, 'home/book-detail.html', context)
    
def get_user_books(request):

    user = request.user

    books_of_user = user.book_set.all()

    return list(books_of_user)


def get_intrested_books(request):

    user = request.user

    intrested_books = user.status_set.filter(status_of_book = "1")  # 1 is for intrested in status model

    return list(intrested_books)

def get_all_books(request):

    all_books = Book.objects.all()

    return list(all_books)

def get_reading_books(request):

    user = request.user

    reading_books = user.status_set.filter(status_of_book = "3") 

    return list(reading_books)

home/templates/home/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'authenticate/back.css' %}"> -->

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet"> 

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet"> 

    {% block css %}

  
    {% endblock %}


 

    <title>    {% block title %} NovelT {% endblock %} </title>
  
    

  </head>
  <body>
<!-- ******************************* NAVBAR ******************************* -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{%url 'home:home'%}">NovelT</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    {% if user.is_authenticated %}

       <form class="form-inline search-btn" style = "margin-left: 490px;">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>

    {% endif %}
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
  
        {% if user.is_authenticated %}
  
        <li class="nav-item">
          <a class="nav-link" href="#">top Picks</a>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            myLibrary
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">e-books</a>
            <a class="dropdown-item" href="#">Audio books </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">myLibrary</a>
          </div>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Search Profile</a>
            <a class="dropdown-item" href="#">Community Tab </a>
            <a class="dropdown-item" href="#">Prefrences </a>
            <a class="dropdown-item" href="{% url 'home:edit-profile' %}">Settings </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'home:profile' %}">Profile</a>
          </div>
        </li>
        <div class="navbar-nav ">
           <a class="nav-item nav-link" href="{% url 'home:logout'%}">logout</a>
        </div>
        {% else %}
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'home:register'%}">Register</a>
          </div>
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'home:login'%}">Login</a>
          </div>
        {% endif %}
      </ul>
    </form>
    </div>
  </nav>
<!-- ******************************* NAVBAR-END ******************************* -->

{% block trend %}

{% endblock %}
 

<!-- <div class="container"> -->
    <!--  url(% static 'authenticate/book.jpeg' %) -->
      <br>
    {% block content %}


    {% endblock %}
<!-- </div> -->
    
</div>


{% block js%}

{% endblock %}
  </body>
}


</html>

home/templates/home/book-detail.html
{% extends 'home/base.html' %}
{% load static %}


{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/book_detail.css' %}">
{% endblock %}


{% block title %} {% endblock %}

{% block content %}
	
	
	<div class = "container">
		<div class = "row my_row">
			<div class = "col-6-md  left_book_detail">

					<div class = "row title_row">
						{{ book }}
					</div>

					<div class = "row author_row">
						<p>Author &nbsp - &nbsp</p> {{ book.author }}
					</div>

					<div class = "row isbn_row">
						<p>ISBN &nbsp - &nbsp</p>{{ book.isbn }}
					</div>

					<div class = "row synopsis_row">
						<p id = "syn">Synopsis &nbsp - &nbsp</p><span id = "syn_text">{{ book.synopsis }}</span>
					</div>

					<div class = "row genere_row">
						<p>Genere &nbsp - &nbsp</p>{{ book.genere }}
					</div>
					
				
			</div>

			<div class = "col-6-md right_book_detail">
					<img src = "{{ book.book_image.url }}" class = "book_cover" alt = "Book Cover">

					<div class = "row buttons">
						<div class = "col-3-md offset-2" id = "read_btn">
							<form action = "" method = "post"> {% csrf_token %}
							 	<button class = "btn btn-outline-info" name = "read_btn" value = "1">Intrested</button>
							
							</form>
						</div>

						<div class = "col-3-md">
							<button class = "btn btn-outline-info" name = "2">Read</button>
						</div>
					</div>
			</div>
		</div>
	</div>
{% endblock %}

home/templates/home/edit-profile.html
{% extends 'home/base.html' %}
{% load static %}

{% block css %}
        
        <link rel="stylesheet" type="text/css" href="{% static '/css/edit-profile.css' %}">
{% endblock %}

{% block title %} Profile {% endblock %}

{% block content %}
	<div class = "container">
	    <form method = 'POST' enctype="multipart/form-data"> {% csrf_token %}

	            {{ user_form.as_p }}
	            {{ profile_form.as_p }}

	            <input type="submit" value="Submit">
	    </form>
    </div>
{% endblock %}

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}  

{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/homepage.css' %}">
{% endblock %}

{% block trend %}
<div class="text-dark" style="background-color: #DAE0E2">


<!-- ******************************* TREND ******************************* -->

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/trend1.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/trend2.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/trend4.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<!-- ******************************* TREND-END ******************************* -->
{% endblock %}
{% block content %}
<div class="container">


{% if user.is_authenticated %}


<!-- <h2> You will like this books </h2> <br/>

 	{% for book in user_intrested_books %}
 		{{ book.books.title }}
 	{% endfor %}

<h2> All books </h2> <br/>
 
 	{% for book in all_books %}
 		{{ book.author }}
 	{% endfor %}
 -->



<div class = "container">
	<h2> Pick any book </h2>
	<div class = "row">
		
			{% for book in all_books %}
				  <a href="{% url 'home:book-detail' book.id %}">
				  	<img src = "{{ book.book_image.url }}" alt = "Book Cover" class = "book_image_home">
				  </a>
			{% endfor %}
	</div>

  {% if user_intrested_books %}
	   <h2> You are intrested in this </h2>
	{% endif %}
  <div class = "row">		
			{% for book in user_intrested_books %}
				<a href="{% url 'home:book-detail' book.books.id %}">
			 		<img src = "{{ book.books.book_image.url }}" alt = "Book Cover" class = "book_image_home">
			 	</a>
			{% endfor %}
	</div>

  {% if reading_books %}
	 <h2> You are currently reading this </h2>
	{% endif %}
  <div class = "row">

		{% for book in reading_books %}
			<a href="{% url 'home:book-detail' book.books.id %}">
 				<img src = "{{ book.books.book_image.url }}" alt = "Book Cover" class = "book_image_home">
 			</a>
		{% endfor %}
	</div>
</div>


<div class = "paginator">


    {% if all_books.paginator.num_pages > 1 %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
     

        <div class = "left_paginatior">
            {% if all_books.has_previous %}
                <li ><a href="?page={{ all_books.previous_page_number }}"><img src = "{% static 'icons/back.png' %}" class = "left_arrow"></a></li>
            {% else %}
            <li class = "disabled"><!-- <img src = "{% static 'icons/back.png' %}" class = "left_arrow"> --></li>
            {% endif %}
        </div>


         <div class = "right_paginatior">
            {% if all_books.has_next %}
      
                <li ><a href="?page={{ all_books.next_page_number }}"><img src = "{% static 'icons/next.png' %}" class = "right_arrow"></a></li>
            {% else %}
              <div class = "next_page">
                <li class="disabled"><a href="#"><!-- <img src = "{% static 'icons/next.png' %}" class = "right_arrow"> --></a></li>

            {% endif %}
          </div>
      
    </ul>
</nav>
{% endif %}
</div>
</ul>
</nav>
</div>





<!-- ******************************* Recent-End ******************************* -->
{% else %}
<br>
LOGIN IS REQUIRED

{% endif %}

</div>
</div>
{% endblock %}

home/templates/home/login.html
{% extends 'home/base.html' %}
{% load static %}

{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/back.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
{% endblock %}

{% block title %} Login {% endblock %}

{% block content %}



 <div class = "login-form effect1">
        <form class = "" method = "POST"> {% csrf_token %}
            <h1>Log in</h1>
           
            <input type = "text" name = "username" placeholder="Username" class = "txtb">
            <input type="password" name="password" placeholder="Password" class = "txtb">

            <input type="submit" value = "Login" class = "signup-btn">
            {% for message in messages %}
                <p id="msg"> {{ message }} </p>
            {% endfor %}
             <p id = "t">New on Novel-T?</p><button class = "btn mybtn"><a href = "{% url 'home:register' %}">Sign up now</a></button>
        </form>
    </div>

{% endblock %}

home/templates/home/profile.html
{% extends 'home/base.html' %}

{% load static %}


{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/profile.css' %}">
{% endblock %}


{% block title %} Profile {% endblock %}

{% block content %}

	<div class = "container"> 
		<div class = "row main_row">
			<div class = "col-4 profile-tab">					
					<div class = "row first_row">

						<div class = "col-5">
							<img src = "{{ user.profile.profile_pic.url|default_if_none:'#' }}" alt = "Profile_PIC" id = "profile_pic">


						</div>

						<div class = "col">
							<h3> {{ user.first_name }}  {{ user.last_name }} </h3>
						</div>

					</div>

					<div class = "row second_row">
						<div class = "col">
							<h3>Followers</h3>
						</div>

						<div class = "col">
							<h3>Following</h3>
						</div>
					</div>

					<div class = "row third_row">

						<div class = "col bio">
							{{ user.profile.bio }}
						</div>
					</div>

					<div class = "row forth_row">

						<div class = "col bio">
							<h4>Genres you like</h4>
							{% for gen in pref_gen_list %}
								<button class = "btn btn-info" disabled>{{ gen }}</button>
							{% endfor %}
							
							
						</div>

					</div>

					
			</div>

			<div class = "col-8 extra-tab" >
				    {% if user_intrested_books %}
						   <h2> You are intrested in this </h2>
					{% else %}
							<h2> You have not discoverd anything yet </h2>
					{% endif %}
					
				  		<div class = "row">		
							{% for book in user_intrested_books %}
								<a href="{% url 'home:book-detail' book.books.id %}">
							 		<img src = "{{ book.books.book_image.url }}" alt = "Book Cover" class = "book_image_home">
							 	</a>
							{% endfor %}
						</div>

					
			</div>
		</div>
	</div>

	<div class = "paginator">


    {% if user_intrested_books.paginator.num_pages > 1 %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
     

        <div class = "left_paginatior">
            {% if user_intrested_books.has_previous %}
                <li ><a href="?page={{ user_intrested_books.previous_page_number }}"><img src = "{% static 'icons/back.png' %}" class = "left_arrow"></a></li>
            {% else %}
            <li class = "disabled"><!-- <img src = "{% static 'icons/back.png' %}" class = "left_arrow"> --></li>
            {% endif %}
        </div>


         <div class = "right_paginatior">
            {% if user_intrested_books.has_next %}
      
                <li ><a href="?page={{ user_intrested_books.next_page_number }}"><img src = "{% static 'icons/next.png' %}" class = "right_arrow"></a></li>
            {% else %}
              <div class = "next_page">
                <li class="disabled"><a href="#"><!-- <img src = "{% static 'icons/next.png' %}" class = "right_arrow"> --></a></li>

            {% endif %}
          </div>
      
    </ul>
</nav>
{% endif %}
</div>
</ul>
</nav>
</div>


{% endblock %}

{% block js %}

	alert("Go to Profile -> setting to setup your profile.");
		
{% endblock %}

home/templates/home/register.html
{% extends 'home/base.html' %}
{% load static %}

{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/back.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/css/register.css' %}">
{% endblock %}

    {% block title %} Signup {% endblock %}

{% block content %}

    <div class = "login-form effect1">
        <form class = "" method = "POST"> {% csrf_token %}
            <h1>Sign Up</h1>

                {{ form.username }}

                {{ form.email }}

                {{ form.password1 }}

                {{ form.password2 }}

            <input type="submit" value = "Create Account" class = "signup-btn">
             {% for message in messages %}
                <p id="msg"> {{ message }} </p>
            {% endfor %}
            <p id="t"> Already have an account? </p><button class = "btn mybtn"><a href = "{% url 'home:login' %}">Log in</a></button>
        </form>
    </div>
       <script type="text/javascript">
        
    var form_fields = document.getElementsByTagName('input')

        // form_fields[0].placeholder='Username';
        // form_fields[1].placeholder='Email';
        form_fields[3].placeholder='Password';
        form_fields[4].placeholder='Re-enter Password';

        for (var field in form_fields){
            form_fields[field].className += ' form-control'
        }
</script>



{% endblock %}

{% block js %}
 
{% endblock %}